# fly.toml app configuration file generated for hpdb-still-meadow-1523 on 2024-01-23T13:04:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hpdb-still-meadow-1523"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
