/*
  Warnings:

  - You are about to drop the column `item` on the `Listing` table. All the data in the column will be lost.
  - Added the required column `productId` to the `Listing` table without a default value. This is not possible if the table is not empty.

*/
-- AlterSequence
ALTER SEQUENCE "Listing_id_seq" MAXVALUE 9223372036854775807;

-- AlterTable
ALTER TABLE "Listing" DROP COLUMN "item";
ALTER TABLE "Listing" ADD COLUMN     "productId" INT4 NOT NULL;

-- CreateTable
CREATE TABLE "Product" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "category" STRING NOT NULL,
    "photo" STRING NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Listing" ADD CONSTRAINT "Listing_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
